name: my_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  intl: ^0.20.2
  excel: ^4.0.6
  path_provider: ^2.1.5
  data_table_2: ^2.5.10
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  flutter_svg: ^2.0.16
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.2
  path: ^1.9.0
  image_picker: ^1.0.7
  printing: ^5.11.1
  pdf: ^3.10.7
  provider: ^6.1.2
  synchronized: ^3.1.0
  network_info_plus: ^4.1.0
  file_picker: ^9.2.1
  permission_handler: ^11.4.0
  share_plus: ^10.1.4
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/malbrose.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: true
    icon_size: 48
    icon_path: "assets/images/malbrose.png"
  macos:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/malbrose.png
